FROM python:3.7-stretch

WORKDIR /usr/src/app
RUN useradd uwsgi
RUN pip install gunicorn==19.9.0
COPY . .
RUN python setup.py install
ENV PYTHONPATH=/usr/src/app/examples/hello_world
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:9000", "app:application"]
